import type { MicroTask } from '@/types/task';

export const MOCK_MICRO_TASKS: MicroTask[] = [
  {
    id: 'mt-01',
    parentTaskId: 'task-01',
    title: '回复 3 封重要邮件',
    estimate: 3,
    requiredContext: 'any',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-02',
    parentTaskId: 'task-01',
    title: '整理今日待办清单',
    estimate: 3,
    requiredContext: 'any',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-03',
    parentTaskId: 'task-02',
    title: '阅读文章前两页并标注重点',
    estimate: 5,
    requiredContext: 'any',
    cognitiveLoad: 'medium',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-04',
    parentTaskId: 'task-02',
    title: '听一段播客并记笔记',
    estimate: 5,
    requiredContext: 'mobile',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-05',
    parentTaskId: 'task-03',
    title: '草拟项目提案大纲',
    estimate: 15,
    requiredContext: 'focused',
    cognitiveLoad: 'high',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-06',
    parentTaskId: 'task-03',
    title: '复习 10 个单词并造句',
    estimate: 5,
    requiredContext: 'any',
    cognitiveLoad: 'medium',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-07',
    parentTaskId: 'task-04',
    title: '做 5 分钟拉伸运动',
    estimate: 5,
    requiredContext: 'any',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-08',
    parentTaskId: 'task-04',
    title: '整理桌面文件',
    estimate: 3,
    requiredContext: 'any',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-09',
    parentTaskId: 'task-05',
    title: '写代码的单元测试',
    estimate: 15,
    requiredContext: 'focused',
    cognitiveLoad: 'high',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-10',
    parentTaskId: 'task-05',
    title: '检查并修复一个 bug',
    estimate: 10,
    requiredContext: 'focused',
    cognitiveLoad: 'high',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-11',
    parentTaskId: 'task-06',
    title: '画一个界面线框图',
    estimate: 15,
    requiredContext: 'focused',
    cognitiveLoad: 'medium',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-12',
    parentTaskId: 'task-06',
    title: '浏览竞品截图并记录灵感',
    estimate: 5,
    requiredContext: 'mobile',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-13',
    parentTaskId: 'task-07',
    title: '冥想 3 分钟',
    estimate: 3,
    requiredContext: 'any',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 1,
  },
  {
    id: 'mt-14',
    parentTaskId: 'task-07',
    title: '写日记：记录今天的三件好事',
    estimate: 5,
    requiredContext: 'any',
    cognitiveLoad: 'low',
    status: 'pending',
    order: 2,
  },
  {
    id: 'mt-15',
    parentTaskId: 'task-08',
    title: '审阅同事的 PR 代码',
    estimate: 15,
    requiredContext: 'focused',
    cognitiveLoad: 'high',
    status: 'pending',
    order: 1,
  },
];
